# no version needed since 2020

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    networks:
      - internal
    ports:
      - '4000:4000'

networks:
  internal:
    driver: bridge
